### ISSUE TITLE
Test items are not collected after Error is raised (within a test_* file)

### ISSUE THREAD

**Issue by guidorice** [guidorice/mojo-pytest#1]
Raising `Error` will prevent subsequent test items from running. To work around this limitation it is recommended to use additional `test_***.mojo` files, rather than writing numerous test items in a test file.

**Comment by lleites** [comment]
I think this is created by the raising of the Error needed to report a failing test. 
We can work around this by just parsing the stdout and to not relying on the return code of the subprocess.
There we have two options, we ask users to print and specific prefix, or use the prefix `ASSERT ERROR` printed by the testing module of Mojo. The nice part about this last version is that we do not need to ask the users to print anything specific, just to use standard lib exceptions. The problem is that we rely on a message we do not have control over, and the Mojo team can easily change (we can write tests to detect if they changed this on newer versions)

I have some working code for a PR about this, we just need to set on the way of signaling a failed assertion.

**Comment by lleites** [comment]
As an example, if I run one of the tests, I get this on my version

```
(.venv) ~/p/mojo-pytest ❯❯❯ mojo run -I . example/tests/mod_a/test_maths.mojo
# maths
# maths more
# maths more: 40
# maths more: 41
# maths more: 42
ASSERT ERROR: bad maths: 42
FAILED bad maths: 42
# maths more: 43
# maths more: 44
# maths more: 45
# maths more: 46
# maths more: 47
# maths more: 48
# maths more: 49
```

ASSERT ERROR comes from Mojo's `testing.assert_true` and FAILED is one possible keyword we can use.

**Comment by guidorice** [comment]
@lleites thanks for the comments on this. Your are correct this issue is caused by the usage of exception handling as required the "Convention":

> Failed tests must raise Mojo Error.

I still like this because now all un-handled exceptions will turn into failed tests. Not only assertion failures or manually printed messages.

> The nice part about this last version is that we do not need to ask the users to print anything specific, just to use standard lib exceptions

It seems that the user would still need to print a token like `print("# test name")` in order to identify successful tests, right? 

Maybe the convention should be more like:

> Failed tests must do either of these:
> - raise Mojo Error
> - Call Mojo's testing.assert_true which as a side effect prints an ASSERT ERROR message.
> - print a FAILED message.

Let me know what you think?

Another nice-to-have would be like [`pytest.raises`](https://docs.pytest.org/en/7.2.x/reference/reference.html#pytest.raises) where we could run a section of code expecting to get a Mojo Error. Let me know what you think about that, I might create a separate enhancement issue for that. It seems like context managers don't work as documented right now in Mojo, but I could be wrong.

**Comment by lleites** [comment]
Ok, let's try to simplify. 
How you signal a test would not change here, you would still need to `print("#" + test_name)`

Failed tests must do either of these:
* raise Mojo Error
* Call Mojo's testing.assert_true which as a side effect prints an ASSERT ERROR message.

I would leave only these two. In case you raise a Mojo error, the follow-up MojoTestItems do not get scanned.
In that case, for me, it is better to encourage just using the standard lib for assertions and say that the plugin is going to take care of the failure. And to explain the case of the exceptions as an advanced approach.

Let me create a PR and we continue the discussion there
